# -*- coding: utf-8 -*-
"""function2.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1ahpzqHXVPzzC3e-N0cOA98CRZJvlybUM
"""

import requests
from bs4 import BeautifulSoup
try:
    def read_content():  
        url = "https://en.wikipedia.org/wiki/Machine_learning"
        response = requests.get(url)
        html = response.content
        soup = BeautifulSoup(response.text, 'html.parser')
        return soup.text
    print(read_content())
    
except KeyboardInterrupt:
    print('You cancelled the operation.')
    
except NameError:
    print('Not Defined')
    
except:
    if(read_content == 'NotFound'):
        print('An error occurred.')
    else:
        print('Error')
