# -*- coding: utf-8 -*-
"""function2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahpzqHXVPzzC3e-N0cOA98CRZJvlybUM
"""

import requests
from bs4 import BeautifulSoup


def read_content():  
    """
    :returns: text-> blah
    :rtype: string
    """

    url = "https://en.wikipedia.org/wiki/Machine_learning"
    response = requests.get(url)
    html = response.content
    soup = BeautifulSoup(html)
    text = soup.text
    return text


print(read_content())